import { createFileRoute } from "@tanstack/react-router";
import { useState } from "react";
import { useMutation } from "@tanstack/react-query";
import { useServerFn } from "@tanstack/react-start";
import { toast } from "sonner";
import { Toaster } from "@/components/ui/sonner";
import { Sparkles, BarChart3, Shield } from "lucide-react";
import { AnalysisForm } from "@/components/business/AnalysisForm";
import { AnalysisResults } from "@/components/business/AnalysisResults";
import { analyzeBusiness, type AnalyzeInput, type BusinessAnalysis } from "@/lib/analyze.functions";

export const Route = createFileRoute("/")({
  head: () => ({
    meta: [
      { title: "GrowthLens — AI Business Assistant for Local Businesses" },
      {
        name: "description",
        content:
          "AI-powered analysis of your local business: spot problems, opportunities, competitor gaps, and a prioritized action plan.",
      },
      { property: "og:title", content: "GrowthLens — AI Business Assistant" },
      {
        property: "og:description",
        content: "Find out why your growth has slowed and what to do about it.",
      },
    ],
  }),
  component: Index,
});

function Index() {
  const analyze = useServerFn(analyzeBusiness);
  const [result, setResult] = useState<BusinessAnalysis | null>(null);

  const mutation = useMutation({
    mutationFn: (data: AnalyzeInput) => analyze({ data }),
    onSuccess: (res) => {
      setResult(res.analysis);
      setTimeout(() => {
        document.getElementById("results")?.scrollIntoView({ behavior: "smooth", block: "start" });
      }, 100);
    },
    onError: (e: Error) => {
      toast.error(e.message || "Something went wrong. Please try again.");
    },
  });

  return (
    <div className="min-h-screen text-foreground" style={{ background: "var(--gradient-bg)" }}>
      <Toaster theme="dark" position="top-right" />

      {/* Decorative glow removed to prevent overlap with heading */}

      <header className="border-b border-border/40 backdrop-blur-sm sticky top-0 z-10 bg-background/40">
        <div className="container mx-auto max-w-6xl flex items-center justify-between px-4 py-4">
          <div className="flex items-center gap-2">
            <div
              className="flex h-9 w-9 items-center justify-center rounded-lg shadow-[var(--shadow-glow)]"
              style={{ background: "var(--gradient-primary)" }}
            >
              <Sparkles className="h-5 w-5 text-primary-foreground" />
            </div>
            <div>
              <div className="font-bold text-foreground leading-tight">GrowthLens</div>
              <div className="text-[10px] uppercase tracking-wider text-muted-foreground">
                AI Business Assistant
              </div>
            </div>
          </div>
          <div className="hidden sm:flex items-center gap-4 text-xs text-muted-foreground">
            <span className="flex items-center gap-1.5">
              <Shield className="h-3.5 w-3.5" /> Private analysis
            </span>
            <span className="flex items-center gap-1.5">
              <BarChart3 className="h-3.5 w-3.5" /> Evidence-based
            </span>
          </div>
        </div>
      </header>

      <main className="container mx-auto max-w-5xl px-4 py-12 md:py-20">
        <section className="text-center mb-12">
          <div className="inline-flex items-center gap-2 rounded-full border border-primary/30 bg-primary/10 px-3 py-1 text-xs text-primary mb-5">
            <Sparkles className="h-3 w-3" /> Powered by AI growth intelligence
          </div>
          <h1 className="relative z-20 text-4xl md:text-6xl font-bold tracking-tight mb-5">
            Why has your growth{" "}
            <span
              className="[background:var(--gradient-primary)] bg-clip-text text-transparent [-webkit-background-clip:text] [-webkit-text-fill-color:transparent]"
            >
              stalled?
            </span>
          </h1>
          <p className="relative z-20 mx-auto max-w-2xl text-lg text-muted-foreground">
            Paste your business details, reviews, and competitors. GrowthLens analyzes everything
            and returns a prioritized action plan you can execute this week.
          </p>
        </section>

        <AnalysisForm isLoading={mutation.isPending} onSubmit={(d) => mutation.mutate(d)} />

        {result && (
          <section id="results" className="mt-14 scroll-mt-24">
            <div className="text-center mb-8">
              <h2 className="text-3xl md:text-4xl font-bold tracking-tight">Your growth report</h2>
              <p className="text-muted-foreground mt-2">
                Generated by AI — review and act on what matters most.
              </p>
            </div>
            <AnalysisResults data={result} />
          </section>
        )}

        <footer className="mt-20 text-center text-xs text-muted-foreground">
          Built with Lovable · Powered by Lovable AI Gateway
        </footer>
      </main>
    </div>
  );
}
